{ config, pkgs, dms, ... }:

{
  # 注意修改这里的用户名与用户目录
  home.username = "mooling";
  home.homeDirectory = "/home/mooling";

  # 设置鼠标指针大小以及字体 DPI
  xresources.properties = {
    "Xcursor.size" = 32;
    "Xft.dpi" = 168;
  };

  # 通过 home.packages 安装一些常用的软件
  # 这些软件将仅在当前用户下可用，不会影响系统级别的配置
  # 建议将所有 GUI 软件，以及与 OS 关系不大的 CLI 软件，都通过 home.packages 安装
  home.packages = with pkgs;[
    # Fonts
    sarasa-gothic

    # Icon theme
    tela-icon-theme

    # GTK theme (DMS 动态主题依赖)
    adw-gtk3

    # Qt theming
    qt6Packages.qt6ct
    libsForQt5.qt5ct
    kdePackages.breeze
    kdePackages.plasma-integration
    kdePackages.qqc2-desktop-style

    # Basic
    python3

    zellij
    fastfetch
    yazi # terminal file manager

    # archives
    zip
    xz
    unzip
    p7zip

    # utils
    ripgrep # recursively searches directories for a regex pattern
    jq # A lightweight and flexible command-line JSON processor
    yq-go # yaml processor https://github.com/mikefarah/yq
    fzf # A command-line fuzzy finder

    # networking tools
    mtr # A network diagnostic tool
    iperf3
    dnsutils  # `dig` + `nslookup`
    ldns # replacement of `dig`, it provide the command `drill`
    aria2 # A lightweight multi-protocol & multi-source command-line download utility
    socat # replacement of openbsd-netcat
    nmap # A utility for network discovery and security auditing
    ipcalc  # it is a calculator for the IPv4/v6 addresses

    # misc
    file
    which
    tree
    gnutar
    zstd

    # nix related
    #
    # it provides the command `nom` works just like `nix`
    # with more details log output
    nix-output-monitor

    # productivity
    hugo # static site generator
    glow # markdown previewer in terminal

    btop  # replacement of htop/nmon
    iotop # io monitoring
    iftop # network monitoring

    # system call monitoring
    strace # system call monitoring
    ltrace # library call monitoring
    lsof # list open files

    # system tools
    sysstat
    lm_sensors # for `sensors` command
    ethtool
    pciutils # lspci
    usbutils # lsusb

    xwayland-satellite

    # common apps
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    qq
    wechat
    wpsoffice-cn
    telegram-desktop
    element-desktop
    google-chrome
    bilibili
    claude-code
  ];

  # git 相关配置
  programs.git = {
    enable = true;
    settings.user.name = "Mooling0602";
    settings.user.email = "clemooling@outlook.com";
  };

  # alacritty - 一个跨平台终端，带 GPU 加速功能
  programs.alacritty = {
    enable = true;
    settings = {
      window = {
        decorations = "None";
        opacity = 0.9;
        padding = { x = 8; y = 4; };
      };
    };
  };

  # 用户头像，DMS 锁屏等处使用
  home.file.".face".source = ../../assets/avatar.jpg;
  home.file.".face.icon".source = ../../assets/avatar.jpg;

  programs.dank-material-shell = {
    enable = true;
    enableDynamicTheming = true;
    enableSystemMonitoring = true;
    niri.enableSpawn = true;
    niri.includes = {
      enable = true;             # Enable config includes hack. Enabled by default.

      override = true;           # If disabled, DMS settings won't be prioritized over settings defined using niri-flake
      originalFileName = "hm";   # A new name (without extension) for the config file generated by niri-flake.
      filesToInclude = [         # Files under `$XDG_CONFIG_HOME/niri/dms` to be included into the new config
        "alttab"                 # Please note that niri will throw an error if any of these files are missing.
        "binds"
        "colors"
        "cursor"
        "layout"
        "outputs"
        "wpblur"
      ];
    };
  };

  programs.niri.settings = {
    environment = {
      QT_QPA_PLATFORMTHEME = "qt6ct";
      QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
    };
  }; 

  # systemd.user.services.niri-flake-polkit.enable = false;

  # This value determines the Home Manager release that your
  # configuration is compatible with. This helps avoid breakage
  # when a new Home Manager release introduces backwards
  # incompatible changes.
  #
  # You can update Home Manager without changing this value. See
  # the Home Manager release notes for a list of state version
  # changes in each release.
  # DMS 启动后自动设置用户头像（头像只在内存中，重启丢失）
  systemd.user.services.dms-set-avatar = {
    Unit = {
      Description = "Set DMS profile avatar after DMS starts";
      After = [ "dms.service" ];
      Wants = [ "dms.service" ];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${pkgs.writeShellScript "dms-set-avatar" ''
        for i in $(seq 1 30); do
          if ${dms.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/dms ipc profile setImage $HOME/nixos-config/assets/avatar.jpg 2>&1 | grep -q SUCCESS; then
            exit 0
          fi
          sleep 1
        done
        exit 1
      ''}";
    };
    Install = {
      WantedBy = [ "dms.service" ];
    };
  };

  home.stateVersion = "25.11";
}
